### ISSUE TITLE
Better TPSA print

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/GTPSA.jl#44]
- [x] The "I" column has got to go.
- [ ] Do not print coefficients whose magnitude is less than `eps` where `eps` is a global that users can set and whose default value is small (like 1e-10).

**Comment by mattsignorelli** [comment]
@DavidSagan  Ok, take a look at the current format and let me know

**Comment by mattsignorelli** [comment]
One change could be to use the sparse monomial order indexing ( 1 0 1 would be 1=>1, 3=>1) for the exponents column. I think this might be a lot cleaner for when the GTPSA has a number of variables above say 10, or we could just default to it

**Comment by mattsignorelli** [comment]
Sparse monomial indexing added, printing also uses `PrettyTables.jl` which takes care of when it might go off the screen. I don't think I will add. the `eps`, because I'm hesitant to add a non constant global and there's some other reasons too we can discuss tomorrow. So the printing should be complete now

**Comment by mattsignorelli** [comment]
Sparse monomial format will be used for printing when nv + np > 6
